# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15c6473ee7f3c404ad2ea6719cd124edfbb50fdeea44cec0060e189c424b039d4bd2e6bb6bc234861c66dd5c90e786e5365f8aa9bf0312468a5442cf7fdeff75

test:
  secret_key_base: 1a7a0f3fe16ba83504ceafe876421a29f2a2303fc22fd658bd53117e79351de1f83901ecc32f4ab88497d5ab965006d5c4114b0781226ef6c15fc7decf29838b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
